### ISSUE TITLE
Split each component color in a file

### ISSUE THREAD

**Issue by matheusrocha89** [matheusrocha89/ionic-flat-colors#32]
Do a refactor to split each component color option in a file like I did with tabs. This will make easier to create the lite version too.

**Comment by petehouston** [comment]
+1 love this buddy

**Comment by matheusrocha89** [comment]
@petehouston the version 0.2.3 that I released today all the scss files are separated

**Comment by matheusrocha89** [comment]
Check the master branch

**Comment by matheusrocha89** [comment]
closed on b3db8a4770ace76a7ac733dcdbe68a37445e9d12
